# Generated by Django 2.0.6 on 2018-07-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0002_auto_20180702_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('userinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userinfo.UserInfo')),
                ('derscription', models.TextField()),
            ],
            bases=('userinfo.userinfo',),
        ),
    ]
