# Generated by Django 2.0.6 on 2018-07-04 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
