# Generated by Django 2.0.6 on 2018-07-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_matching_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matching',
            old_name='nickname',
            new_name='user',
        ),
    ]
